[project]
name = "ec2-greencost"
version = "0.1.0"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
]

[tool.pytest.ini_options]
addopts = "-q --cov=ec2_greencost"

[tool.coverage.run]
branch = true
source = ["ec2_greencost"]
omit = ["tests/*", "*/__init__.py"]

[tool.coverage.report]
fail_under = 70
show_missing = true

[tool.setuptools.packages.find]
where = ["src"]

